### ISSUE TITLE
wrong catching of Exceptions in async mode

### ISSUE THREAD

**Issue by callejerog** [axel-events/axel#8]
When the Event is used with async = True than any exception occurred during handler execution is catched at lib level and never raised to the main.
Chanching the following code of _execute(_args, *_kw) function as indicated resolves the issue:

ORIG (line 207):
except:
    if not self.asynch:
        with rlock:
            result.append((False, self._error(sys.exc_info()), h))

NEW:
except Exception as e:
    if not self.asynch:
        with rlock:
            result.append((False, self._error(sys.exc_info()), h))
    else:
        raise e

**Comment by mayerwin** [comment]
Hi @callejerog, thanks for reporting this issue. We are working on releasing a fix.
